apiVersion: 1

datasources:
  - name: PencilLine InfluxDB
    uid: influxdb-pencils
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true
      httpMode: POST
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
